* Clojure weekly #1

** Articles

In memory database in 500 lines of code:
http://aosabook.org/en/500L/an-archaeology-inspired-database.html

How to improve dev startup time:
https://clojure.org/guides/dev_startup_time

A RealWorld Comparison of Front-End Frameworks 2020

A comparison of Front-End frameworks where the goal is to implement a
working RealWorld app. Spoiler: Re-frame with ClojureScript fares very
well.
https://medium.com/dailyjs/a-realworld-comparison-of-front-end-frameworks-2020-4e50655fe4c1

** Software releases

Joker v0.15.0
https://github.com/candid82/joker/releases/tag/v0.15.0

4clojure that runs in your shell as a babashka script:
https://github.com/porkostomus/4bb

Spire 0.1.0-alpha.2 released
https://github.com/epiccastle/spire/releases/tag/v0.1.0-alpha.2

cryogen-core-fork is now able to serve resources from classpath instead only serving resources from filesystem:
https://github.com/DomainDrivenArchitecture/cryogen-core

babashka.curl: A tiny curl wrapper via idiomatic Clojure, inspired by clj-http, Ring and friends.
https://github.com/borkdude/babashka.curl

first version of trident.firestore, a ClojureScript wrapper for Firebase's Firestore DB
https://github.com/jacobobryant/trident/blob/master/doc/firestore.md

Kaocha has had a few releases this week
See https://github.com/lambdaisland/kaocha/releases/tag/v0.0-597
and https://github.com/lambdaisland/kaocha/releases/tag/v0.0-601

https://github.com/lambdaisland/kaocha/releases

** Tools

You know of jq and Borkdude's jet, bb, sci, but how about Haskell flavoured jl:
https://github.com/chrisdone/jl

** In Emacs world

https://github.com/sogaiu/alc.index-defs will generate TAGS (etags) / tags (ctags) for clojure source projects.

** In Vim

New release of vim-iced ver 1.1.0, Clojure Interactive Development Environment for Vim8/Neovim
https://twitter.com/uochan/status/1237852655025704960

** In shadow-cljs

*** NPM lib usage
Alwasy use quotes when requiring libs from NPM:

https://clojurians-log.clojureverse.org/clojurescript/2020-03-05/1583405327.353100

*** Externs
How to find out what externs are missing from your project and how to
enable their infering:
https://clojurians-log.clojureverse.org/shadow-cljs/2020-03-05/1583420259.459100


*** Cordova
Sample app on how to use shadow-cljs with Cordova
https://github.com/thheller/cordova-cljs



** Events
Clojure Data Science web meeting on March 26th, 5pm-7pm UTC
https://twitter.com/scicloj/status/1237844104643395589

** Meetup video
Ludovic Courtès of the Guix-Jupyter project
https://scicloj.github.io/posts/2020-03-07-guix-jupyter/

** Conferences

*** Clojure Days CFP
Submit your proposal by March 15: https://www.papercall.io/dcd20

*** ClojuTRE 2020 Call for Speakers
Submit your proposal by April 19th: https://forms.gle/bous14pCUVFy1hyJ9

*** re:Clojure 2020
re:Clojure is being organised for the fall 2020.
You heard it here first :)

** Workshop for learning Clojure

Dug this up from the Clojure IRC archive, it's a course is based on
previous courses given at Helsinki Metropolia University of Applied
Sciences in 2012 and at University of Helsinki CS department in 2011
and 2012: https://iloveponies.github.io/
